### ISSUE TITLE
"No official docker base images used" for tensorflow/tensorflow

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-base-image-policy#214]
"Supported Docker base image policy" tells me "No official Docker base images being used in any of the Dockerfiles"

for `tensorflow/tensorflow`

Is this not an official image?  https://hub.docker.com/r/tensorflow/tensorflow/

**Comment by cdupuis** [comment]
No, it is not. Official images have a Official Image badge. See https://hub.docker.com/_/mongo for an example. 

I once more think this is a docs issue in that we are missing Glossary of terms.

**Comment by cdupuis** [comment]
More on Official Images at https://docs.docker.com/docker-hub/official_images/

**Comment by slimslenderslacks** [comment]
I wonder if the tensorflow maintainters have a concept of "supported" tags.  Probably not one that's easy to discover.

**Comment by cdupuis** [comment]
I checked the Docker Hub page and the underlying repo and can't find something that would be machine readable. 

But should we start building up a database of supported tags for non official docker images?
