### ISSUE TITLE
Default Config:  Audit everything - apply policy to nothing

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-base-image-policy#358]
Proposal:
* leave `pinningRequired`, `pinningPullRequests`, and `supportedTagRequired` under control of dso
* introduce a second `repoFilter` parameter (named `audit`)
* dso sets the `audit` repoFilter to `includes: nil` (the value that indicates all repos) when enabling the skill
* dso continues to leave the existing `repoFilter` unset entirely

Does this give this policy the context it needs to, by default, audit everything, during onboarding, and to only begin creating checkruns, and pull requests after the second `repoFilter` parameters is set?

Testing this on another skill, it does appear to work
* new repos during onboarding and indexed, and the isRepoSelected? rule selects them

**Comment by slimslenderslacks** [comment]
> How does the 2nd repo filter work with the repo-selected rule in the subscription?

The `repo-selected?` rule will unify if _any_ repoFilter parameter matches the `?repo`

> The code doesn’t do anything with the repoFilter so we would need to somehow do something in the subscription to distinguish between repos that should only get audits and those that should get audits and check runs/PRs.

@kipz was mentioning that this could be where you separate out the CheckRun creation but I think you could also just check the second repoFilter at runtime for now (if that's the fastest way for you to support this)

> cd I do not currently understand what the second repo filter is going to be used for? Are we going to allow user to configure two different sets of repos? Or do we ever expect the audit repo filter to get some orgs/repos configured?

The second repoFilter is not user-facing at first.  Only the `audit` repo filter is user facing.  The first repoFilter is really just there to make sure that we can emphasize the case where users let us see "discover" how we can help them but still let them narrow down their testing to a small set (the example is what happened with Marlette last week - 300 repos and lots of interesting audit data, but they only want to test pinning PRs on 4 repos)

> I thought that we would audit every visible repo but only raise check runs when they are enabled on repos selected by the repo filter. Is that understanding not correct?

You might still at some point want to reduce the set of repos that show up in the audit too.  We won't expose that at first.

> And assuming the 2nd repo filter is needed, couldn’t we just use a 2nd skill configuration with different settings: one enabling audit on all or a set of repos; 2nd config for check runs on another set of repos?

I don't know.  I always think of second configurations as being non-overlapping, but I'll ask now.

**Comment by slimslenderslacks** [comment]
By the way, would the second configuration idea be "easier" for you?

**Comment by cdupuis** [comment]
2nd configuration would mean no work as I currently see it. 

Enablement of check runs and audit can be controlled separately via parameters. So setting up two different configurations should be straight forward. 

Especially given I would need to implement repo filtering in the skill for which I'm sure I don't know all the rules right now.

**Comment by slimslenderslacks** [comment]
We are discussing this with Danny right now.

**Comment by slimslenderslacks** [comment]
One question that came up was "What happens when we really do want to support multiple configurations?".  I guess you're proposing that the "audit" configuration would be created at the beginning and would never be touched.  And then the second policy configuration would be the one that was configured by dso when the policy is updated, and the existing repoFilter is changed.

Is that right?

**Comment by cdupuis** [comment]
Yes, one untouchable audit config for all repos (or whatever we decide to audit or surface) and one for the user facing features (checkrun, pr creation) with a repo filter.

**Comment by slimslenderslacks** [comment]
So you would request that one "audit" configuration is created when the skill is enabled and that the parameters pinningRequired, pinningPullRequests, and supportedTagRequired parameters are all set to false.
Subscriptions for your "audit" configuration will transact the sarif data only.  Subscriptions for your policy configuration will exclusively handle CheckRuns and PRs.

For docker file policy, I decided to move the PRs and CheckRuns to watch the sarif results so that they could be potentially be aggregated into single PRs in the future.  But I've currently had to use runtime-filtering because the `skill-repo-selected?` rule will observe either repoFilter parameter.  We could add another rule that allows you to specify which repoFilter parameter to observe as well.

I think you can go with the second configuration - I just wanted to give you some additional context in case that changes anything for you.

**Comment by cdupuis** [comment]
I would suggest the following two configurations to cover the audit use case:

### `policy-audit`

Internal configuration for audit. Not user facing.

`pinningRequired` > `false`
`pinningAudit` > `true`
`pinningPullRequests` > `false`
`pinningAptPullRequests` > `false`
`supportedTagRequired` > `false`
`supportedTagAudit` > `true`
`acceptRequired` > `false` or default
`linkingRequired` > `false` or default
`repoFilter` > selected org or repos for audit (most likely null to indicate audit all)

### `policy-cfg`

User-facing configuration

`pinningRequired` > `true` or toggle state
`pinningAudit` > `false`
`pinningPullRequests` > `true` or toggle state
`pinningAptPullRequests` > `false`
`supportedTagRequired` > `true` or toggle state
`supportedTagAudit` > `false`
`acceptRequired` > `false` or default
`linkingRequired` > `false` or default
`repoFilter` > selected org or repos

**Comment by slenderslack** [comment]
^ @dansmithy this is the final decision here.  You should create this policy-audit configuration when enabling the docker-base-image-policy. At that point, we should be able to verify that we can aggressively turn off the prs and checkruns in the policy-cfg and still see the onboarding.

**Comment by cdupuis** [comment]
Let's hold off making those changes. I want to try the approach @slimslenderslacks implemented to stay closer together with our skills.

**Comment by cdupuis** [comment]
I've made a new version stable that uses two repo filters and code level repo filtering to figure out what needs to happen on a repository.
