### ISSUE TITLE
Migrate from `docker/file` to `git/file`

### ISSUE THREAD

**Issue by kipz** [atomist-skills/docker-base-image-policy#366]
We are finally ready for this migration:

`docker.file.line/file` will point to a `git/file` and `git.commit/file` points to many `git/file`

**Comment by kipz** [comment]
@cdupuis don't want to create a bunch of issues for all affected skills, so we can assume this is for all the TS/DSO skills if that's OK? 

We are ready for this now, and it's becoming quite important (obviously not as urgent as any DSO vulnerability stuff). It's a prerequisite for the BOM stuff.

**Comment by slimslenderslacks** [comment]
@cdupuis we now need to get this one done and have verified that it's working and ready for you to do.

**Comment by cdupuis** [comment]
@kipz @slimslenderslacks what's the equivalent for `:docker.file.line/file`?

**Comment by kipz** [comment]
It's the same, but points to a git/file
