### ISSUE TITLE
Required Docker Capabilities

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-base-image-policy#37]
To discuss: is the docker registry configuraiton in the docker-base-image-policy still required?

**Comment by cdupuis** [comment]
Made optional in d309b9e

**Comment by slimslenderslacks** [comment]
Re-opening.  Using a new "scope=subscription" or "scope=ingestion" may give us the ability to request a capability, without needing to add the capability selection to the configuration screen.  cc @kipz @dansmithy

**Comment by cdupuis** [comment]
Closing again since @kipz fixed it.
